package ru.storage;

import io.art.tarantool.model.field.TarantoolField;
import io.art.tarantool.model.record.TarantoolRecord;
import io.art.tarantool.model.transaction.dependency.TarantoolTransactionDependency;
import io.art.tarantool.space.TarantoolSpace;
import io.art.tarantool.space.TarantoolSpaceImplementation.SelectRequest;
import ru.model.Model;
import ru.model.StorageExampleModel;

public class ExampleStorageInterfaces {

  public interface StorageExampleModelFieldNames {
    TarantoolField id = new TarantoolField(1, "id");
    TarantoolField data = new TarantoolField(2, "data");
  }

  public interface StorageExampleModelSpace extends TarantoolSpace<StorageExampleModel, Integer> {

    TarantoolRecord<StorageExampleModel> getBySecondary(Integer key);

    TarantoolRecord<StorageExampleModel> getBySecondary(
        TarantoolTransactionDependency keyDependency);

    SelectRequest<StorageExampleModel> selectBySecondary(Integer key);

    SelectRequest<StorageExampleModel> selectBySecondary(
        TarantoolTransactionDependency keyDependency);
  }

  public interface ModelFieldNames {
    TarantoolField FInteger = new TarantoolField(1, "FInteger");
    TarantoolField FCharacter = new TarantoolField(2, "FCharacter");
    TarantoolField FShort = new TarantoolField(3, "FShort");
    TarantoolField FByte = new TarantoolField(4, "FByte");
    TarantoolField FBoolean = new TarantoolField(5, "FBoolean");
    TarantoolField FLong = new TarantoolField(6, "FLong");
    TarantoolField FDouble = new TarantoolField(7, "FDouble");
    TarantoolField FFloat = new TarantoolField(8, "FFloat");
    TarantoolField FBInteger = new TarantoolField(9, "FBInteger");
    TarantoolField FBShort = new TarantoolField(10, "FBShort");
    TarantoolField FBByte = new TarantoolField(11, "FBByte");
    TarantoolField FBBoolean = new TarantoolField(12, "FBBoolean");
    TarantoolField FBLong = new TarantoolField(13, "FBLong");
    TarantoolField FBString = new TarantoolField(14, "FBString");
    TarantoolField FBDouble = new TarantoolField(15, "FBDouble");
    TarantoolField FBFloat = new TarantoolField(16, "FBFloat");
    TarantoolField FUUID = new TarantoolField(17, "FUUID");
    TarantoolField FlocalDateTime = new TarantoolField(18, "FlocalDateTime");
    TarantoolField FzonedDateTime = new TarantoolField(19, "FzonedDateTime");
    TarantoolField FDate = new TarantoolField(20, "FDate");
    TarantoolField FAint = new TarantoolField(21, "FAint");
    TarantoolField FAchar = new TarantoolField(22, "FAchar");
    TarantoolField FAshort = new TarantoolField(23, "FAshort");
    TarantoolField FAbyte = new TarantoolField(24, "FAbyte");
    TarantoolField FAboolean = new TarantoolField(25, "FAboolean");
    TarantoolField FAlong = new TarantoolField(26, "FAlong");
    TarantoolField FAdouble = new TarantoolField(27, "FAdouble");
    TarantoolField FAfloat = new TarantoolField(28, "FAfloat");
    TarantoolField FABInteger = new TarantoolField(29, "FABInteger");
    TarantoolField FABCharacter = new TarantoolField(30, "FABCharacter");
    TarantoolField FABShort = new TarantoolField(31, "FABShort");
    TarantoolField FABByte = new TarantoolField(32, "FABByte");
    TarantoolField FABBoolean = new TarantoolField(33, "FABBoolean");
    TarantoolField FABLong = new TarantoolField(34, "FABLong");
    TarantoolField FABString = new TarantoolField(35, "FABString");
    TarantoolField FABDouble = new TarantoolField(36, "FABDouble");
    TarantoolField FABFloat = new TarantoolField(37, "FABFloat");
    TarantoolField FCInteger = new TarantoolField(38, "FCInteger");
    TarantoolField FCCharacter = new TarantoolField(39, "FCCharacter");
    TarantoolField FCShort = new TarantoolField(40, "FCShort");
    TarantoolField FCByte = new TarantoolField(41, "FCByte");
    TarantoolField FCBoolean = new TarantoolField(42, "FCBoolean");
    TarantoolField FCLong = new TarantoolField(43, "FCLong");
    TarantoolField FCString = new TarantoolField(44, "FCString");
    TarantoolField FCDouble = new TarantoolField(45, "FCDouble");
    TarantoolField FCFloat = new TarantoolField(46, "FCFloat");
    TarantoolField FLInteger = new TarantoolField(47, "FLInteger");
    TarantoolField FLCharacter = new TarantoolField(48, "FLCharacter");
    TarantoolField FLShort = new TarantoolField(49, "FLShort");
    TarantoolField FLByte = new TarantoolField(50, "FLByte");
    TarantoolField FLBoolean = new TarantoolField(51, "FLBoolean");
    TarantoolField FLLong = new TarantoolField(52, "FLLong");
    TarantoolField FLString = new TarantoolField(53, "FLString");
    TarantoolField FLDouble = new TarantoolField(54, "FLDouble");
    TarantoolField FLFloat = new TarantoolField(55, "FLFloat");
    TarantoolField FSInteger = new TarantoolField(56, "FSInteger");
    TarantoolField FSCharacter = new TarantoolField(57, "FSCharacter");
    TarantoolField FSShort = new TarantoolField(58, "FSShort");
    TarantoolField FSByte = new TarantoolField(59, "FSByte");
    TarantoolField FSBoolean = new TarantoolField(60, "FSBoolean");
    TarantoolField FSLong = new TarantoolField(61, "FSLong");
    TarantoolField FSString = new TarantoolField(62, "FSString");
    TarantoolField FSDouble = new TarantoolField(63, "FSDouble");
    TarantoolField FSFloat = new TarantoolField(64, "FSFloat");
    TarantoolField FMInteger = new TarantoolField(65, "FMInteger");
    TarantoolField FMCharacter = new TarantoolField(66, "FMCharacter");
    TarantoolField FMShort = new TarantoolField(67, "FMShort");
    TarantoolField FMByte = new TarantoolField(68, "FMByte");
    TarantoolField FMBoolean = new TarantoolField(69, "FMBoolean");
    TarantoolField FMLong = new TarantoolField(70, "FMLong");
    TarantoolField FMString = new TarantoolField(71, "FMString");
    TarantoolField FMDouble = new TarantoolField(72, "FMDouble");
    TarantoolField pArgFMFloat = new TarantoolField(73, "pArgFMFloat");
    TarantoolField FModel = new TarantoolField(74, "FModel");
    TarantoolField FAModel = new TarantoolField(75, "FAModel");
    TarantoolField FLModel = new TarantoolField(76, "FLModel");
    TarantoolField FLLModel = new TarantoolField(77, "FLLModel");
    TarantoolField FLSModel = new TarantoolField(78, "FLSModel");
    TarantoolField FLCModel = new TarantoolField(79, "FLCModel");
    TarantoolField FLMModel = new TarantoolField(80, "FLMModel");
    TarantoolField FLAModel = new TarantoolField(81, "FLAModel");
    TarantoolField FALModel = new TarantoolField(82, "FALModel");
    TarantoolField FSModel = new TarantoolField(83, "FSModel");
    TarantoolField FSLModel = new TarantoolField(84, "FSLModel");
    TarantoolField FSSModel = new TarantoolField(85, "FSSModel");
    TarantoolField FSCModel = new TarantoolField(86, "FSCModel");
    TarantoolField FSMModel = new TarantoolField(87, "FSMModel");
    TarantoolField FSAModel = new TarantoolField(88, "FSAModel");
    TarantoolField FASModel = new TarantoolField(89, "FASModel");
    TarantoolField FCModel = new TarantoolField(90, "FCModel");
    TarantoolField FCLModel = new TarantoolField(91, "FCLModel");
    TarantoolField FCSModel = new TarantoolField(92, "FCSModel");
    TarantoolField FCCModel = new TarantoolField(93, "FCCModel");
    TarantoolField FCMModel = new TarantoolField(94, "FCMModel");
    TarantoolField FCAModel = new TarantoolField(95, "FCAModel");
    TarantoolField FACModel = new TarantoolField(96, "FACModel");
    TarantoolField FMModel = new TarantoolField(97, "FMModel");
    TarantoolField FMAModel = new TarantoolField(98, "FMAModel");
    TarantoolField FMLModel = new TarantoolField(99, "FMLModel");
    TarantoolField FMSModel = new TarantoolField(100, "FMSModel");
    TarantoolField FMCModel = new TarantoolField(101, "FMCModel");
    TarantoolField FMMModel = new TarantoolField(102, "FMMModel");
    TarantoolField FAMModel = new TarantoolField(103, "FAMModel");
    TarantoolField FCCMModel = new TarantoolField(104, "FCCMModel");
    TarantoolField FCLMModel = new TarantoolField(105, "FCLMModel");
    TarantoolField FCSMModel = new TarantoolField(106, "FCSMModel");
    TarantoolField FCMMModel = new TarantoolField(107, "FCMMModel");
    TarantoolField FCLMAModel = new TarantoolField(108, "FCLMAModel");
    TarantoolField FCSMAModel = new TarantoolField(109, "FCSMAModel");
    TarantoolField FCCMAModel = new TarantoolField(110, "FCCMAModel");
    TarantoolField FCMAModel = new TarantoolField(111, "FCMAModel");
    TarantoolField FGModel = new TarantoolField(112, "FGModel");
    TarantoolField FGSModel = new TarantoolField(113, "FGSModel");
    TarantoolField FAGModel = new TarantoolField(114, "FAGModel");
    TarantoolField FASAGModel = new TarantoolField(115, "FASAGModel");
    TarantoolField FLGModel = new TarantoolField(116, "FLGModel");
    TarantoolField FSGModel = new TarantoolField(117, "FSGModel");
    TarantoolField FCGModel = new TarantoolField(118, "FCGModel");
    TarantoolField FMGMModel = new TarantoolField(119, "FMGMModel");
    TarantoolField FLazyString = new TarantoolField(120, "FLazyString");
    TarantoolField FLazyLong = new TarantoolField(121, "FLazyLong");
    TarantoolField FCLazyLong = new TarantoolField(122, "FCLazyLong");
    TarantoolField FLazyCLong = new TarantoolField(123, "FLazyCLong");
    TarantoolField FCLazyCLong = new TarantoolField(124, "FCLazyCLong");
    TarantoolField FLazyLongA = new TarantoolField(125, "FLazyLongA");
    TarantoolField FLazyALong = new TarantoolField(126, "FLazyALong");
    TarantoolField FLazyCLongA = new TarantoolField(127, "FLazyCLongA");
    TarantoolField FLazyCALong = new TarantoolField(128, "FLazyCALong");
    TarantoolField FLazyCLAMultiA = new TarantoolField(129, "FLazyCLAMultiA");
    TarantoolField MSLazyMCMLongMultiA = new TarantoolField(130, "MSLazyMCMLongMultiA");
    TarantoolField FOptionalString = new TarantoolField(131, "FOptionalString");
    TarantoolField FOptionalLong = new TarantoolField(132, "FOptionalLong");
    TarantoolField FCOptionalLong = new TarantoolField(133, "FCOptionalLong");
    TarantoolField FOptionalCLong = new TarantoolField(134, "FOptionalCLong");
    TarantoolField FCOptionalCLong = new TarantoolField(135, "FCOptionalCLong");
    TarantoolField FOptionalLongA = new TarantoolField(136, "FOptionalLongA");
    TarantoolField FOptionalALong = new TarantoolField(137, "FOptionalALong");
    TarantoolField FOptionalCLongA = new TarantoolField(138, "FOptionalCLongA");
    TarantoolField FOptionalCALong = new TarantoolField(139, "FOptionalCALong");
    TarantoolField FOptionalCLAMultiA = new TarantoolField(140, "FOptionalCLAMultiA");
    TarantoolField MSOptionalMCMLongMultiA = new TarantoolField(141, "MSOptionalMCMLongMultiA");
    TarantoolField SASOptionalMCMLongMultiA = new TarantoolField(142, "SASOptionalMCMLongMultiA");
    TarantoolField QASOptionalMCMLongMultiA = new TarantoolField(143, "QASOptionalMCMLongMultiA");
    TarantoolField DSSOptionalMCMLongMultiA = new TarantoolField(144, "DSSOptionalMCMLongMultiA");
    TarantoolField IASOptionalMCMLongMultiA = new TarantoolField(145, "IASOptionalMCMLongMultiA");
    TarantoolField ISSOptionalMCMLongMultiA = new TarantoolField(146, "ISSOptionalMCMLongMultiA");
    TarantoolField IMSOptionalMCMLongMultiA = new TarantoolField(147, "IMSOptionalMCMLongMultiA");
    TarantoolField FStringStream = new TarantoolField(148, "FStringStream");
    TarantoolField FValue = new TarantoolField(149, "FValue");
    TarantoolField FEntity = new TarantoolField(150, "FEntity");
    TarantoolField FAValue = new TarantoolField(151, "FAValue");
    TarantoolField FAEntity = new TarantoolField(152, "FAEntity");
    TarantoolField FCValue = new TarantoolField(153, "FCValue");
    TarantoolField FCAValue = new TarantoolField(154, "FCAValue");
  }

  public interface ModelSpace extends TarantoolSpace<Model, Long> {

    TarantoolRecord<Model> getBySomeIndex(Boolean key);

    TarantoolRecord<Model> getBySomeIndex(TarantoolTransactionDependency keyDependency);

    SelectRequest<Model> selectBySomeIndex(Boolean key);

    SelectRequest<Model> selectBySomeIndex(TarantoolTransactionDependency keyDependency);
  }

  public interface FieldNames {
    String id = "id";
    String data = "data";
    String FInteger = "FInteger";
    String FCharacter = "FCharacter";
    String FShort = "FShort";
    String FByte = "FByte";
    String FBoolean = "FBoolean";
    String FLong = "FLong";
    String FDouble = "FDouble";
    String FFloat = "FFloat";
    String FBInteger = "FBInteger";
    String FBShort = "FBShort";
    String FBByte = "FBByte";
    String FBBoolean = "FBBoolean";
    String FBLong = "FBLong";
    String FBString = "FBString";
    String FBDouble = "FBDouble";
    String FBFloat = "FBFloat";
    String FUUID = "FUUID";
    String FlocalDateTime = "FlocalDateTime";
    String FzonedDateTime = "FzonedDateTime";
    String FDate = "FDate";
    String FAint = "FAint";
    String FAchar = "FAchar";
    String FAshort = "FAshort";
    String FAbyte = "FAbyte";
    String FAboolean = "FAboolean";
    String FAlong = "FAlong";
    String FAdouble = "FAdouble";
    String FAfloat = "FAfloat";
    String FABInteger = "FABInteger";
    String FABCharacter = "FABCharacter";
    String FABShort = "FABShort";
    String FABByte = "FABByte";
    String FABBoolean = "FABBoolean";
    String FABLong = "FABLong";
    String FABString = "FABString";
    String FABDouble = "FABDouble";
    String FABFloat = "FABFloat";
    String FCInteger = "FCInteger";
    String FCCharacter = "FCCharacter";
    String FCShort = "FCShort";
    String FCByte = "FCByte";
    String FCBoolean = "FCBoolean";
    String FCLong = "FCLong";
    String FCString = "FCString";
    String FCDouble = "FCDouble";
    String FCFloat = "FCFloat";
    String FLInteger = "FLInteger";
    String FLCharacter = "FLCharacter";
    String FLShort = "FLShort";
    String FLByte = "FLByte";
    String FLBoolean = "FLBoolean";
    String FLLong = "FLLong";
    String FLString = "FLString";
    String FLDouble = "FLDouble";
    String FLFloat = "FLFloat";
    String FSInteger = "FSInteger";
    String FSCharacter = "FSCharacter";
    String FSShort = "FSShort";
    String FSByte = "FSByte";
    String FSBoolean = "FSBoolean";
    String FSLong = "FSLong";
    String FSString = "FSString";
    String FSDouble = "FSDouble";
    String FSFloat = "FSFloat";
    String FMInteger = "FMInteger";
    String FMCharacter = "FMCharacter";
    String FMShort = "FMShort";
    String FMByte = "FMByte";
    String FMBoolean = "FMBoolean";
    String FMLong = "FMLong";
    String FMString = "FMString";
    String FMDouble = "FMDouble";
    String pArgFMFloat = "pArgFMFloat";
    String FModel = "FModel";
    String FAModel = "FAModel";
    String FLModel = "FLModel";
    String FLLModel = "FLLModel";
    String FLSModel = "FLSModel";
    String FLCModel = "FLCModel";
    String FLMModel = "FLMModel";
    String FLAModel = "FLAModel";
    String FALModel = "FALModel";
    String FSModel = "FSModel";
    String FSLModel = "FSLModel";
    String FSSModel = "FSSModel";
    String FSCModel = "FSCModel";
    String FSMModel = "FSMModel";
    String FSAModel = "FSAModel";
    String FASModel = "FASModel";
    String FCModel = "FCModel";
    String FCLModel = "FCLModel";
    String FCSModel = "FCSModel";
    String FCCModel = "FCCModel";
    String FCMModel = "FCMModel";
    String FCAModel = "FCAModel";
    String FACModel = "FACModel";
    String FMModel = "FMModel";
    String FMAModel = "FMAModel";
    String FMLModel = "FMLModel";
    String FMSModel = "FMSModel";
    String FMCModel = "FMCModel";
    String FMMModel = "FMMModel";
    String FAMModel = "FAMModel";
    String FCCMModel = "FCCMModel";
    String FCLMModel = "FCLMModel";
    String FCSMModel = "FCSMModel";
    String FCMMModel = "FCMMModel";
    String FCLMAModel = "FCLMAModel";
    String FCSMAModel = "FCSMAModel";
    String FCCMAModel = "FCCMAModel";
    String FCMAModel = "FCMAModel";
    String FGModel = "FGModel";
    String FGSModel = "FGSModel";
    String FAGModel = "FAGModel";
    String FASAGModel = "FASAGModel";
    String FLGModel = "FLGModel";
    String FSGModel = "FSGModel";
    String FCGModel = "FCGModel";
    String FMGMModel = "FMGMModel";
    String FLazyString = "FLazyString";
    String FLazyLong = "FLazyLong";
    String FCLazyLong = "FCLazyLong";
    String FLazyCLong = "FLazyCLong";
    String FCLazyCLong = "FCLazyCLong";
    String FLazyLongA = "FLazyLongA";
    String FLazyALong = "FLazyALong";
    String FLazyCLongA = "FLazyCLongA";
    String FLazyCALong = "FLazyCALong";
    String FLazyCLAMultiA = "FLazyCLAMultiA";
    String MSLazyMCMLongMultiA = "MSLazyMCMLongMultiA";
    String FOptionalString = "FOptionalString";
    String FOptionalLong = "FOptionalLong";
    String FCOptionalLong = "FCOptionalLong";
    String FOptionalCLong = "FOptionalCLong";
    String FCOptionalCLong = "FCOptionalCLong";
    String FOptionalLongA = "FOptionalLongA";
    String FOptionalALong = "FOptionalALong";
    String FOptionalCLongA = "FOptionalCLongA";
    String FOptionalCALong = "FOptionalCALong";
    String FOptionalCLAMultiA = "FOptionalCLAMultiA";
    String MSOptionalMCMLongMultiA = "MSOptionalMCMLongMultiA";
    String SASOptionalMCMLongMultiA = "SASOptionalMCMLongMultiA";
    String QASOptionalMCMLongMultiA = "QASOptionalMCMLongMultiA";
    String DSSOptionalMCMLongMultiA = "DSSOptionalMCMLongMultiA";
    String IASOptionalMCMLongMultiA = "IASOptionalMCMLongMultiA";
    String ISSOptionalMCMLongMultiA = "ISSOptionalMCMLongMultiA";
    String IMSOptionalMCMLongMultiA = "IMSOptionalMCMLongMultiA";
    String FStringStream = "FStringStream";
    String FValue = "FValue";
    String FEntity = "FEntity";
    String FAValue = "FAValue";
    String FAEntity = "FAEntity";
    String FCValue = "FCValue";
    String FCAValue = "FCAValue";
  }
}
