name: ART Java Publish
on:
  push:
    branches:
      - main
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 1.8 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean publish --max-workers 8 --parallel -Ppublish.properties=${publishProperties}
        env:
          publishProperties: ${{ secrets.publishProperties }}
